version: '3.9'

services:
  server:
    environment:
      - NODE_ENV=local
    hostname: events_server
    container_name: events_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: base
    ports:
      - 5500:5500
    command: >
      sh -c "npm run dev"
    volumes:
      - ./src/src:/app/src

  events_db:
    image: mariadb:11.2.3
    hostname: events_db
    container_name: events_db
    restart: unless-stopped
    env_file:
      - src/local.env
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3311:3306